export const CREATE_CARDS = "CREATE_CARDS";
export const SET_LOADING = "SET_LOADING";
export const SET_STARTED = "SET_STARTED";
export const CREATE_STOCK_AND_TABLEAU = "CREATE_STOCK_AND_TABLEAU";
export const SET_SELECTED = "SET_SELECTED";
export const CLEAR_SELECTED = "CLEAR_SELECTED";
export const MOVE_CARDS = "MOVE_CARDS";
export const ADD_CARDS = "ADD_CARDS";
